_extends: .github

repository:
  name: node-fs-writefile-promise
  description: Promise version of fs.writefile
  topics: node, fs, writefile, promise
  homepage: https://github.com/ahmadnassri/node-fs-writefile-promise
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
